# Generated by Django 5.2.3 on 2025-10-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
        ('trips', '0002_trip_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together={('trip', 'day_number')},
        ),
    ]
