# Generated by Django 5.2.3 on 2025-10-02 05:48

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa'), ('ticket', 'Ticket/Boarding Pass'), ('booking', 'Booking Confirmation'), ('insurance', 'Travel Insurance'), ('itinerary', 'Itinerary'), ('map', 'Map'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_size', models.IntegerField(editable=False, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
