# Generated by Django 5.2.3 on 2025-10-02 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('group', 'Group')], default='personal', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='split_between',
            field=models.ManyToManyField(blank=True, related_name='expenses_shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
