# Generated by Django 5.2.3 on 2025-10-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('INR', 'Indian Rupee (₹)')], default='USD', max_length=3),
        ),
    ]
